import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "./providers";
import { BottomNav } from "@/components/BottomNav";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen max-w-xl mx-auto bg-gray-50`}
      >
        <div className="p-4 h-full bg-white">
          <Providers>{children}</Providers>
        </div>
        <BottomNav />
      </body>
    </html>
  );
}
