import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "./providers";

import "reset-css";
import "./globals.css";

// NanumSquareNeo 폰트 등록
const nanumSquareNeo = localFont({
  src: [
    {
      path: "./fonts/NanumSquareNeo-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-nanum-square-neo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${nanumSquareNeo.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
